apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: exdemo
  region: ap-south-1

vpc:
  subnets:
    private:
      ap-south-1b: { id: subnet-e58fafa9 }
      ap-south-1c: { id: subnet-a79bf1dc }
      ap-south-1a: { id: subnet-1195677a }

nodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: t2.medium
    desiredCapacity: 1
    privateNetworking: true
  - name: ng-2-builders
    labels: { role: builders }
    instanceType: t2.medium
    desiredCapacity: 1
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true
